version: '3'

services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: votelog
      POSTGRES_PASSWORD: no8MYWi3rsGjQbfYTKF7CwoG7fKhfE
      POSTGRES_DB: votelog

  data-import-init:
    build: .
    command: init --user votelog --host database --password no8MYWi3rsGjQbfYTKF7CwoG7fKhfE --database votelog
    depends_on:
      - database

  data-import-sync:
    build: .
    command: sync --user votelog --host database --password no8MYWi3rsGjQbfYTKF7CwoG7fKhfE --database votelog
    depends_on:
      - database
